spring:
  application:
    name: zuul-server

server:
  port: 2222

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/
  instance:
    prefer-ip-address: true #开启注册ip到eureka服务列表

zuul:
  ignoredServices: '*'
  routes:
    plat:
      path: /plat/**
      serviceId: plat-server
  prefix: /services #前缀